[project]
name = "chartbots-fastapi"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Mengsyue Amao Tsai", email = "mengsyue.tsai@outlook.com" }
]
dependencies = [
    "fastapi[standard]>=0.115.0",
    "line-bot-sdk>=3.13.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []

[tool.rye.scripts]
dev = "uvicorn src.main:app --reload --host 127.0.0.1 --port 10002"
start = "uvicorn src.main:app --host 0.0.0.0 --port 10002"
